### ISSUE TITLE
eden: modify blog link icon and text

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#127]
now that I'm thinking, I believe we should change this icon to a link icon (eg: 
![image](https://user-images.githubusercontent.com/79721020/117133889-d5379a00-ad72-11eb-9558-352e10a62678.png)) and then replace the Blog word with the url... thoughts? not for this PR too.

_Originally posted by @sparkplug0025 in https://github.com/eoscommunity/Eden/pull/120#discussion_r626481574_

**Comment by sparkplug0025** [comment]
@NorseGaud here: https://github.com/eoscommunity/Eden/blob/main/packages/webapp/src/members/components/member-social-links.tsx#L48-L56

**Comment by NorseGaud** [comment]
Ah, an area I can't seem to access from the app even after logging in -- is that right?

**Comment by sparkplug0025** [comment]
Actually you can. Just click in any member that has a blog, eg: https://eden-dev.vercel.app/members/test255.edev

![image](https://user-images.githubusercontent.com/79721020/117653667-b2d2c180-b162-11eb-8cf2-acf9874f05e2.png)

See the blog link? it should be changed to the url icon and have the domain displayed there instead.

**Comment by NorseGaud** [comment]
Oh wow, I totally missed that. Thanks!

**Comment by brandonfancher** [comment]
Icon replaced (thanks @NorseGaud). We still need the word "Blog" replaced with the URL. Keeping this issue open.

**Comment by sparkplug0025** [comment]
@brandonfancher I think we should have some formatting here just to be beautiful displayed...

Let's say we have the following scenarios:
- moreequalanimals.com
- https://moreequalanimals.com
- https://moreequalanimals.com/this-is-a-great-article-written-by-daniel-larimer-about-xyz

I think for the first 2 cases we should display the domain (not the url), so: moreequalanimals.com

For the last one, it would be a long string and probably break the ui. So I believe something like `moreequalanimals.com/this-is-a-great...` would be proper.

Any thoughts?

**Comment by NorseGaud** [comment]
> For the last one, it would be a long string and probably break the ui. So I believe something like `moreequalanimals.com/this-is-a-great...` would be proper.

Could you clarify what "break the ui" means? What would break? (I'm partially asking because I hate when sites shorten URLs like that :) )

**Comment by brandonfancher** [comment]
Yeah, good point. I'm fine with this proposal...drop the protocol and truncate with ellipsis after certain length. 

> @brandonfancher I think we should have some formatting here just to be beautiful displayed...
> 
> Let's say we have the following scenarios:
> 
> * moreequalanimals.com
> * https://moreequalanimals.com
> * https://moreequalanimals.com/this-is-a-great-article-written-by-daniel-larimer-about-xyz
> 
> I think for the first 2 cases we should display the domain (not the url), so: moreequalanimals.com
> 
> For the last one, it would be a long string and probably break the ui. So I believe something like `moreequalanimals.com/this-is-a-great...` would be proper.

**Comment by sparkplug0025** [comment]
> > For the last one, it would be a long string and probably break the ui. So I believe something like `moreequalanimals.com/this-is-a-great...` would be proper.
> 
> Could you clarify what "break the ui" means? What would break? ( I'm partially asking because I hate when sites shorten URLs like that :) )

The link would push around other social links. If we do a soft word-wrap, it will break lines (vs other social handles which have only a single line) or if we just accept the long lengthy link it will push the other social links block to the right... I meant break the general alignment.

I'm fine with full address, but we would need to make sure it does not look nasty on small screens...

**Comment by NorseGaud** [comment]
@brandonfancher this seems complete. What do you think?

**Comment by brandonfancher** [comment]
I'm just keeping it open because it says the word "Blog" still...which feels antiquated and too narrowly scoped. I'm willing to close this if we can find a better word...heck, even the word "Link" is better than "Blog." Any ideas?

**Comment by NorseGaud** [comment]
What if users can set it to whatever they want when they're adding links?

**Comment by brandonfancher** [comment]
> What if users can set it to whatever they want when they're adding links? May be abused, but that seems like the most logical choice

Yeah, that's a logical idea for sure. But it does require changing our schema for social links and extra, divergent, work. I just pushed #316, which at least (for now) resolves the terminology dissonance by changing the word "Blog" to "Website" or "Personal website."
