### ISSUE TITLE
🚝 Create scripts to initialize a new AtomicAssets NFTs Collection and Schema for Eden

### ISSUE THREAD

**Issue by sparkplug0025** [eoscommunity/Eden#16]
This script would facilitate developers to spin up new contracts and using new Eden collections/schemas for tests.

**Comment by swatanabe** [comment]
Does this need anything outside of smart contract land?  If not, it can be handled as part of the genesis process.

**Comment by sparkplug0025** [comment]
You are right. If we embed the nft collection/schema creation in the genesis we don't need it! :)

**Comment by swatanabe** [comment]
The contract now handles this
