### ISSUE TITLE
SocketService slow down the page loading + throws a bunch of errorss

### ISSUE THREAD

**Issue by NorseGaud** [eoscommunity/Eden#163]
Each page-load of the app (started from `yarn dev --stream`) seems to be taking quite a while to load.

<img width="1315" alt="Screen Shot 2021-05-09 at 9 49 45 PM" src="https://user-images.githubusercontent.com/5896030/117596116-9b6ae880-b110-11eb-9246-b45468f5c591.png">

**Comment by sparkplug0025** [comment]
It should be linked with #143 -- Scatter is causing these troubles in our dev envs...

**Comment by NorseGaud** [comment]
Good ol' Scatter ;)

**Comment by brandonfancher** [comment]
Since this is covered by #143, I'm going to close this for now. It's on the record in #143 as a reference.
