### ISSUE TITLE
🎨 📟 Implement IPFS Pinning Limits

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#198]
We're implementing IPFS uploading from our frontend (instead of telling users to go to Pinata.cloud and do it themselves.) This is how we do it:
1. User selects image or video and frontend uploads it to Infura's public IPFS gateway.
2. Transaction is sent to our backend serverless function, which inspects and does some integrity checks on the IPFS CID and then pins the file to our Pinata.cloud account.
Right now, there are no file size checks. A user could mistakenly upload a 100MB image, and we'd happily pin it in Pinata and pay for that storage.

We should implement sane limits by:
1. Check file size in the frontend and error out if image/video is too large. 
2. Because users could get around that if they want, inspect the file metadata in our serverless function prior to pinning it to Pinata.cloud and refuse to pin anything larger than our limits.

**Comment by sparkplug0025** [comment]
Profile Images: 1mb
Videos: 100mb
