### ISSUE TITLE
🎨 Link to the Peace Treaty in Notion!

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#231]
We should have a link on our home page or footer...or maybe better--a separate page--containing the Peace Treaty and Bylaws. Thomas has some ideas on where this goes.

People are asking where the Peace Treaty they're supposed to be agreeing to is located! While it's in the Ricardian, they don't know to look there, and they shouldn't have to wait until sign time to read it!

**Comment by sparkplug0025** [comment]
I'm going to take a first stab by adding the link to notion on the Footer. Then we can groom it properly with what we really want in terms of adding it inside our page with new issue tickets. 

Some options:
- Just a plain static page with jsx.
- A Markdown file that we can use to allow non-developers to propose changes and write to it, inside our repo.
- Usage of a headless CMS in case we think we need more sophisticated tools for the job of maintaining these static documents.
