### ISSUE TITLE
🎨 📜 Change inductendorse to inductendors

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#274]
The changes are being made in the contract. We need to:
* Update the UI code
* Roll out the UI update in lockstep with the contract change.

**Comment by sparkplug0025** [comment]
Hey actually @tbfleming already did this [here](https://github.com/eoscommunity/Eden/blob/main/packages/webapp/src/inductions/transactions.ts#L136)! We just need to deploy the contract and probably the UI is broken for now in dev :P

**Comment by sparkplug0025** [comment]
Deployed!

**Comment by brandonfancher** [comment]
Ah, missed that. Great!
