### ISSUE TITLE
eden: [general] fail to upload videos when using SoftKey

### ISSUE THREAD

**Issue by sparkplug0025** [eoscommunity/Eden#513]
We hit some issues when trying to upload a video transaction using the SoftKey. 
To reproduce:
- login using a password (softkey)
- try to upload an induction video or an election round video
- you should see an error like this:
![image](https://user-images.githubusercontent.com/79721020/134335491-a7595daf-0418-4a90-a79d-6acd40b2b4aa.png)

**Comment by brandonfancher** [comment]
Fixed in #557
