### ISSUE TITLE
eden: figure out IPFS pinning solution

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#54]
We're issuing NFTs. They'll have associated assets. We also have induction videos. While we may (as part of v0) handle much of this manually and host the IPFS assets ourselves, we should work to identify a better solution to the IPFS pinning problem.

This is about identifying and documenting the solution. We will implement it later.

**Comment by sparkplug0025** [comment]
Starting a draft here: https://www.notion.so/edenos/IPFS-v0-e3e02ff2293e40e9b0ddf6e64d60f246

**Comment by sparkplug0025** [comment]
The upload forms through our backend is done with #194 #196  and #202 
Now we need to figure out a garbage collection method (cronjobs, listening eos nodes, own database etc.)

**Comment by brandonfancher** [comment]
We will also need to think about how to upload larger election videos...most will come in around 50 minutes and likely blow past the 100 MB limit imposed by Infura.
