### ISSUE TITLE
🖼 NFT: Create NFT Collection for Mainnet

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#68]
1. get final mainnet account
1. create eden collection in AA
1. create members schema in AA
1. fill out the AA [Collection Whitelist Request](https://support.pink.gg/hc/en-us/requests/new?ticket_form_id=360001444300) to get rid of the ugly banner

**Comment by sparkplug0025** [comment]
When creating the schema please hit me a message, we should adopt the best practices suggested by Rob

**Comment by brandonfancher** [comment]
The contract now automatically creates the collection and scheme when the `genesis` action is run.
