### ISSUE TITLE
🖼 Update NFT property names to align with best practices

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#78]
Can we change from `edenacc` to `account` across the board? (to support multiple communities)

@brandonfancher I think that according to the best practices meeting we need these two changes:
1. rename `inductionvid` to `video`
2. new copyrights (or attributions) field? to follow the suggestion to credit the author of the picture art?

_Originally posted by @sparkplug0025 in https://github.com/eoscommunity/Eden/pull/74#discussion_r622049839_

**Comment by brandonfancher** [comment]
Agreed. I'll comb back through our call with Rob too to see if we're missing anything.

**Comment by sparkplug0025** [comment]
just as a headsup we already renamed edenacc to account and inductionvid to video. the pending one is the copyright/attributions.

**Comment by brandonfancher** [comment]
Cool. Let's call it `attributions`.

**Comment by sparkplug0025** [comment]
@swatanabe it's going to be a string, optional, a new attribute on the nfts... if you can tackle the contract side I can add this field in the UI. @brandonfancher what do you think is a good max length for this one?
