### ISSUE TITLE
assess which wallets we want to support

### ISSUE THREAD

**Issue by sparkplug0025** [eoscommunity/Eden#80]
for now we support only Anchor...

Which ones should we support?
- Scatter
- Wombat
- Lynx
- etc..

**Comment by brandonfancher** [comment]
One of the new `UALProvider` authenticators is erroring out. In dev mode, it's loud (see below). I don't think it impacts user experience in prod mode though. But it is annoying in dev mode.

![image](https://user-images.githubusercontent.com/7911424/117218774-cfbd6c80-add1-11eb-94c5-dcc91eaf0393.png)
![image](https://user-images.githubusercontent.com/7911424/117218789-d6e47a80-add1-11eb-804b-6323be6be56e.png)

I think it's Scatter. Not sure.
