### ISSUE TITLE
📜 Remove a member's pending invites to an inductee once their induction is completed

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#82]
Right now, if `inviter` has two invitations out to `invitee` and `invitee` completes one of them, the `inviter`'s dashboard still shows the other one as pending...even though the `invitee` is no longer eligible to receive or act on invitations.

We should clear out any active invitations to `invitee` once they are successfully inducted.

**Comment by swatanabe** [comment]
I think this needs to be handled in the front end.  The contract does need to clear the records, but it should not do so in the same transaction that completes the invitation as the number of pending invitations is only bounded by active members.

**Comment by brandonfancher** [comment]
Closing this for now in favor of a more general approach referenced in #88. Either way, UI will need to handle this case while awaiting scheduled cleanups.
